# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: ["commit"]
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: 3dca5ac3ebf85346a8383485badfca816ca3f84a
    hooks: 
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: > 
          (?x)^(
          tests/testthat/in/.*\.R|
          renv/.*
          )$
